apiVersion: v1
kind: Secret
metadata:
  name: iris-app-secrets
  namespace: iris-web
  labels:
    site: iris
type: Opaque
data:
  POSTGRES_USER: cmFwdG9y
  POSTGRES_PASSWORD: TnB5OFRtUm5uSm14WA==
  POSTGRES_ADMIN_USER: cmFwdG9y
  POSTGRES_ADMIN_PASSWORD: TnB5OFRtUm5uSm14WA==
  POSTGRES_PORT: NTQzMg==
  IRIS_SECRET_KEY: ZVFNdnVTbTI2U0hVd0Vx
  IRIS_SECURITY_PASSWORD_SALT: Y3c3dFVuQnp6Z3pZdVU=
