apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: iris-web
  name: iris-app-claim
  labels:
    site: iris
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: iris-sc
  resources:
    requests:
      storage: 30Gi