apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:  
  name: admin-kustomize
  labels:
    site: iris
resources:
  - namespace.yml
  - storageclass.yml
  - app-claim.yml
  - worker-claim.yml
  - psqk-claim.yml